import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import {
  applyFilters,
  computeByChannel,
  computeKPIs,
  computeWeeklyTrend,
  getAllAppointments,
  type Appointment,
  type Filters,
} from "../../../client/src/features/plan-dashboard-replacement/data/mockData";
import { BASE_CURRENCY, isSupportedCurrency, type SupportedCurrency } from "@shared/currency";
import { currencyService, type ExchangeRateSnapshot } from "../../domain/currencyService";

export type ExportPlan = "essential" | "pro" | "enterprise";
export type ExportAppointment = Appointment;
export type ExportPayload = {
  clinicName: string;
  plan: ExportPlan;
  language: "PT" | "EN" | "ES" | string;
  currency: string;
  filters: Record<string, string>;
  appointments?: ExportAppointment[];
};

type SummaryRow = { label: string; value: string; trend: string; status: string; color: ReturnType<typeof rgb> };
type ExecutiveNote = { title: string; body: string; color: ReturnType<typeof rgb> };
type ChartBlock = {
  section: string;
  title: string;
  analysis: string;
  sourceKpis: string;
  sourceSystem: string;
  kind: "barLine" | "dualAxis" | "grouped" | "financial";
  labels: string[];
  a: number[];
  b: number[];
  c?: number[];
  d?: number[];
  target?: number;
  labelA?: string;
  labelB?: string;
  labelC?: string;
  labelD?: string;
  colorA?: ReturnType<typeof rgb>[] | ReturnType<typeof rgb>;
  valueFormat?: "money" | "percent" | "integer";
  targetLabel?: string;
};

type ReportDefinition = {
  subtitle: string;
  summary: SummaryRow[];
  notes: ExecutiveNote[];
  priorities: string[];
  blocks: ChartBlock[];
};

type ReportCopy = {
  reportTitle: string;
  executiveTitle: string;
  overview: string;
  generatedAt: string;
  page: string;
  of: string;
  autoGenerated: string;
  demoData: string;
  kpi: string;
  value: string;
  trend: string;
  status: string;
  ceoPriorities: string;
  notes: {
    northStar: string;
    mainRisk: string;
    opportunity: string;
    cashEfficiency: string;
  };
  statuses: {
    onTrack: string;
    inProgress: string;
    healthy: string;
    attention: string;
    excellent: string;
    monitor: string;
    promoter: string;
    neutral: string;
    belowTarget: string;
    nearTarget: string;
    growing: string;
    evolving: string;
  };
  sections: {
    revenue: string;
    funnel: string;
    finance: string;
    agenda: string;
    projects: string;
    cash: string;
    channels: string;
  };
  charts: {
    mrrVsTarget: string;
    churnVsNrr: string;
    pipeline: string;
    grossNetMargin: string;
    noShowVsOccupancy: string;
    npsVsMilestones: string;
    cashConversion: string;
    channelRevenue: string;
  };
  legends: {
    target: string;
    gross: string;
    net: string;
    margin: string;
    leakage: string;
    occupancy: string;
    noShow: string;
    leads: string;
    calls: string;
    sprints: string;
    setups: string;
    nrr: string;
    churn: string;
    mrr: string;
    nps: string;
    milestones: string;
    revenueK: string;
    cac: string;
  };
  sourcesTitle: string;
  sourceHeaders: {
    module: string;
    kpis: string;
    system: string;
  };
};

const W = 595.28;
const H = 841.89;
const MX = 42;
const CW = W - MX * 2;
const DARK = rgb(0.059, 0.09, 0.165);
const BLUE = rgb(0.145, 0.388, 0.922);
const GREEN = rgb(0.086, 0.639, 0.29);
const RED = rgb(0.863, 0.149, 0.149);
const AMBER = rgb(0.851, 0.467, 0.024);
const ORANGE = rgb(0.945, 0.451, 0.086);
const ORANGE_SOFT = rgb(0.984, 0.694, 0.447);
const GRAY = rgb(0.392, 0.455, 0.545);
const GRID = rgb(0.886, 0.91, 0.949);
const LIGHT = rgb(0.973, 0.98, 0.988);
const WHITE = rgb(1, 1, 1);

const COPY: Record<ExportPayload["language"], ReportCopy> = {
  PT: {
    reportTitle: "Dashboard KPI",
    executiveTitle: "Relatorio Executivo",
    overview: "VISAO GERAL",
    generatedAt: "Gerado em",
    page: "Pagina",
    of: "de",
    autoGenerated: "Gerado automaticamente",
    demoData: "Dados simulados para demonstracao do pipeline KPI -> PDF",
    kpi: "KPI",
    value: "Valor",
    trend: "Tendencia",
    status: "Status",
    ceoPriorities: "Prioridades do CEO para o proximo ciclo",
    notes: {
      northStar: "North Star",
      mainRisk: "Risco Principal",
      opportunity: "Oportunidade",
      cashEfficiency: "Eficiencia Caixa",
    },
    statuses: {
      onTrack: "No trilho",
      inProgress: "Em andamento",
      healthy: "Saudavel",
      attention: "Atencao",
      excellent: "Excelente",
      monitor: "Monitorar",
      promoter: "Promotor",
      neutral: "Neutro",
      belowTarget: "Abaixo meta",
      nearTarget: "Perto da meta",
      growing: "Crescendo",
      evolving: "Em evolucao",
    },
    sections: {
      revenue: "C1 RECEITA",
      funnel: "C2 FUNIL",
      finance: "FINANCEIRO",
      agenda: "AGENDA",
      projects: "C3 PROJETOS",
      cash: "CAIXA & EFICIENCIA",
      channels: "CANAIS",
    },
    charts: {
      mrrVsTarget: "MRR Mensal vs. North Star",
      churnVsNrr: "Churn Mensal x Net Revenue Retention",
      pipeline: "Pipeline Comercial - Leads -> Calls -> Sprints -> Setups",
      grossNetMargin: "Faturamento Bruto x Receita Liquida x Margem",
      noShowVsOccupancy: "No-Show Rate x Ocupacao da Agenda",
      npsVsMilestones: "NPS Medio x Marcos no Prazo",
      cashConversion: "Conversao de Receita em Caixa Liquido",
      channelRevenue: "Receita por Canal x No-Show por Origem",
    },
    legends: {
      target: "Meta",
      gross: "Bruto",
      net: "Liquido",
      margin: "Margem",
      leakage: "Vazamento",
      occupancy: "Ocupacao",
      noShow: "No-Show",
      leads: "Leads",
      calls: "Calls",
      sprints: "Sprints",
      setups: "Setups",
      nrr: "NRR",
      churn: "Churn",
      mrr: "MRR",
      nps: "NPS",
      milestones: "Marcos",
      revenueK: "Receita k",
      cac: "CAC",
    },
    sourcesTitle: "FONTES DOS DADOS",
    sourceHeaders: {
      module: "Modulo",
      kpis: "KPIs",
      system: "Sistema de Origem",
    },
  },
  EN: {
    reportTitle: "KPI Dashboard",
    executiveTitle: "Executive Report",
    overview: "OVERVIEW",
    generatedAt: "Generated at",
    page: "Page",
    of: "of",
    autoGenerated: "Automatically generated",
    demoData: "Demo data for the KPI to PDF pipeline",
    kpi: "KPI",
    value: "Value",
    trend: "Trend",
    status: "Status",
    ceoPriorities: "CEO priorities for the next cycle",
    notes: {
      northStar: "North Star",
      mainRisk: "Main Risk",
      opportunity: "Opportunity",
      cashEfficiency: "Cash Efficiency",
    },
    statuses: {
      onTrack: "On track",
      inProgress: "In progress",
      healthy: "Healthy",
      attention: "Attention",
      excellent: "Excellent",
      monitor: "Monitor",
      promoter: "Promoter",
      neutral: "Neutral",
      belowTarget: "Below target",
      nearTarget: "Near target",
      growing: "Growing",
      evolving: "Evolving",
    },
    sections: {
      revenue: "C1 REVENUE",
      funnel: "C2 FUNNEL",
      finance: "FINANCE",
      agenda: "AGENDA",
      projects: "C3 PROJECTS",
      cash: "CASH & EFFICIENCY",
      channels: "CHANNELS",
    },
    charts: {
      mrrVsTarget: "Monthly MRR vs. North Star",
      churnVsNrr: "Monthly Churn x Net Revenue Retention",
      pipeline: "Commercial Pipeline - Leads -> Calls -> Sprints -> Setups",
      grossNetMargin: "Gross Revenue x Net Revenue x Margin",
      noShowVsOccupancy: "No-Show Rate x Agenda Occupancy",
      npsVsMilestones: "Average NPS x On-Time Milestones",
      cashConversion: "Revenue to Net Cash Conversion",
      channelRevenue: "Channel Revenue x No-Show by Source",
    },
    legends: {
      target: "Target",
      gross: "Gross",
      net: "Net",
      margin: "Margin",
      leakage: "Leakage",
      occupancy: "Occupancy",
      noShow: "No-Show",
      leads: "Leads",
      calls: "Calls",
      sprints: "Sprints",
      setups: "Setups",
      nrr: "NRR",
      churn: "Churn",
      mrr: "MRR",
      nps: "NPS",
      milestones: "Milestones",
      revenueK: "Revenue k",
      cac: "CAC",
    },
    sourcesTitle: "DATA SOURCES",
    sourceHeaders: {
      module: "Module",
      kpis: "KPIs",
      system: "Source System",
    },
  },
  ES: {
    reportTitle: "Dashboard KPI",
    executiveTitle: "Informe Ejecutivo",
    overview: "VISION GENERAL",
    generatedAt: "Generado en",
    page: "Pagina",
    of: "de",
    autoGenerated: "Generado automaticamente",
    demoData: "Datos simulados para la demo del pipeline KPI a PDF",
    kpi: "KPI",
    value: "Valor",
    trend: "Tendencia",
    status: "Estado",
    ceoPriorities: "Prioridades del CEO para el proximo ciclo",
    notes: {
      northStar: "North Star",
      mainRisk: "Riesgo Principal",
      opportunity: "Oportunidad",
      cashEfficiency: "Eficiencia de Caja",
    },
    statuses: {
      onTrack: "En ruta",
      inProgress: "En progreso",
      healthy: "Saludable",
      attention: "Atencion",
      excellent: "Excelente",
      monitor: "Monitorear",
      promoter: "Promotor",
      neutral: "Neutro",
      belowTarget: "Debajo de meta",
      nearTarget: "Cerca de la meta",
      growing: "Creciendo",
      evolving: "Evolucionando",
    },
    sections: {
      revenue: "C1 INGRESOS",
      funnel: "C2 EMBUDO",
      finance: "FINANZAS",
      agenda: "AGENDA",
      projects: "C3 PROYECTOS",
      cash: "CAJA Y EFICIENCIA",
      channels: "CANALES",
    },
    charts: {
      mrrVsTarget: "MRR Mensual vs. North Star",
      churnVsNrr: "Churn Mensual x Net Revenue Retention",
      pipeline: "Pipeline Comercial - Leads -> Calls -> Sprints -> Setups",
      grossNetMargin: "Facturacion Bruta x Ingreso Neto x Margen",
      noShowVsOccupancy: "No-Show x Ocupacion de Agenda",
      npsVsMilestones: "NPS Medio x Hitos a Tiempo",
      cashConversion: "Conversion de Ingresos en Caja Neta",
      channelRevenue: "Ingresos por Canal x No-Show por Origen",
    },
    legends: {
      target: "Meta",
      gross: "Bruto",
      net: "Neto",
      margin: "Margen",
      leakage: "Fuga",
      occupancy: "Ocupacion",
      noShow: "No-Show",
      leads: "Leads",
      calls: "Calls",
      sprints: "Sprints",
      setups: "Setups",
      nrr: "NRR",
      churn: "Churn",
      mrr: "MRR",
      nps: "NPS",
      milestones: "Hitos",
      revenueK: "Ingreso k",
      cac: "CAC",
    },
    sourcesTitle: "FUENTES DE DATOS",
    sourceHeaders: {
      module: "Modulo",
      kpis: "KPIs",
      system: "Sistema de Origen",
    },
  },
};

function localeOf(language: ExportPayload["language"]) {
  return language === "EN" ? "en-US" : language === "ES" ? "es-ES" : "pt-BR";
}

function normalizeLanguage(language?: string): "PT" | "EN" | "ES" {
  const normalized = (language || "PT").trim().toUpperCase();
  return normalized === "EN" || normalized === "ES" ? normalized : "PT";
}

function normalizeCurrency(currency?: string): SupportedCurrency {
  const normalized = (currency || "BRL").trim().toUpperCase();
  return isSupportedCurrency(normalized) ? normalized : BASE_CURRENCY;
}

function fmtAt(payload: ExportPayload) {
  const locale = localeOf(payload.language);
  return new Date().toLocaleString(locale, { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" });
}
function currencySymbol(currency: string, locale: string) {
  const parts = new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: 0 }).formatToParts(0);
  return parts.find((part) => part.type === "currency")?.value ?? currency;
}
function fMoney(v: number, currency: string, locale: string) {
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(Math.round(v));
}
function fMoneyShort(v: number, currency: string, locale: string, language: ExportPayload["language"]) {
  if (Math.abs(v) < 1000) return fMoney(v, currency, locale);
  const short = new Intl.NumberFormat(locale, { minimumFractionDigits: 0, maximumFractionDigits: 1 }).format(v / 1000);
  const suffix = language === "EN" ? "k" : language === "ES" ? " mil" : " mil";
  return `${currencySymbol(currency, locale)} ${short}${suffix}`;
}
function fPct(v: number, locale: string) { return `${v.toLocaleString(locale, { minimumFractionDigits: 1, maximumFractionDigits: 1 })}%`; }
function fInt(v: number, locale: string) { return Math.round(v).toLocaleString(locale); }
function clamp(v: number, min: number, max: number) { return Math.max(min, Math.min(max, v)); }
function wrap(text: string, font: PDFFont, size: number, maxWidth: number) {
  const words = (text || "").replace(/\s+/g, " ").trim().split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= maxWidth) current = next;
    else { if (current) lines.push(current); current = word; }
  }
  if (current) lines.push(current);
  return lines;
}
function text(page: PDFPage, value: string, x: number, y: number, font: PDFFont, size: number, color: ReturnType<typeof rgb>, maxWidth?: number, lineHeight = 12) {
  if (!maxWidth) { page.drawText(value, { x, y, font, size, color }); return y - lineHeight; }
  let cursor = y;
  for (const line of wrap(value, font, size, maxWidth)) { page.drawText(line, { x, y: cursor, font, size, color }); cursor -= lineHeight; }
  return cursor;
}
function labels(count = 8) {
  const out: string[] = [];
  const now = new Date();
  for (let i = count - 1; i >= 0; i -= 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    out.push(d.toLocaleDateString("pt-BR", { month: "short", year: "2-digit" }).replace(".", ""));
  }
  return out;
}
function localizedLabels(count: number, locale: string) {
  const out: string[] = [];
  const now = new Date();
  for (let i = count - 1; i >= 0; i -= 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    out.push(d.toLocaleDateString(locale, { month: "short", year: "2-digit" }).replace(".", ""));
  }
  return out;
}
function pad(series: number[], fallback: number, target = 8) {
  if (series.length >= target) return series.slice(-target);
  if (series.length === 0) return Array.from({ length: target }, () => fallback);
  const missing = target - series.length;
  const pre = Array.from({ length: missing }, (_, i) => series[0] * (0.84 + ((i + 1) / (missing + 1)) * 0.12));
  return [...pre, ...series].map((v) => Number(v.toFixed(2)));
}
function toFilters(input: Record<string, string>): Filters {
  return { period: input.period || "30d", channel: input.channel || "", professional: input.professional || "", procedure: input.procedure || "", status: input.status || "", unit: input.unit || "", severity: input.severity || "" };
}
function resolveAppointments(payload: ExportPayload) {
  if (payload.appointments && payload.appointments.length > 0) return payload.appointments;
  return applyFilters(getAllAppointments(), toFilters(payload.filters));
}
function buildReport(payload: ExportPayload, rates?: ExchangeRateSnapshot): ReportDefinition {
  const language = normalizeLanguage(payload.language);
  const copy = COPY[language];
  const locale = localeOf(language);
  const currency = normalizeCurrency(payload.currency);
  const convertMoneyValue = (value: number) => currencyService.convertFromBase(value, currency, rates ?? {
    base: BASE_CURRENCY,
    fetchedAt: new Date().toISOString(),
    provider: "fallback",
    stale: true,
    rates: {
      BRL: 1,
      USD: currency === "USD" ? 1 : Number.NaN,
      EUR: currency === "EUR" ? 1 : Number.NaN,
      ARS: currency === "ARS" ? 1 : Number.NaN,
      CLP: currency === "CLP" ? 1 : Number.NaN,
      COP: currency === "COP" ? 1 : Number.NaN,
      MXN: currency === "MXN" ? 1 : Number.NaN,
      PEN: currency === "PEN" ? 1 : Number.NaN,
      UYU: currency === "UYU" ? 1 : Number.NaN,
    },
  });
  const data = resolveAppointments(payload);
  const trend = computeWeeklyTrend(data);
  const channel = computeByChannel(data);
  const base = computeKPIs(data);
  const l = localizedLabels(8, locale);
  const gross = pad(trend.map((w) => convertMoneyValue(w.grossRevenue)), convertMoneyValue(base.grossRevenue / 6));
  const net = pad(trend.map((w) => convertMoneyValue(w.netRevenue)), convertMoneyValue(base.netRevenue / 6));
  const cancel = pad(trend.map((w) => w.cancelRate), base.cancelRate);
  const returns = pad(trend.map((w) => w.returnRate), base.returnRate);
  const noShow = pad(trend.map((w) => w.noShowRate), base.noShowRate);
  const occupancy = pad(trend.map((w) => w.occupancyRate), base.occupancyRate);
  const leads = pad(trend.map((w) => w.leads), Math.max(8, Math.round(base.leads / 4)));
  const nps = pad(trend.map((w) => w.avgNPS * 10), base.avgNPS * 10);
  const mrr = net.map((v, i) => Number((v * (0.9 + i * 0.025)).toFixed(0)));
  const nrr = returns.map((v, i) => clamp(100 + v * 0.55 - cancel[i] * 0.9, 80, 140));
  const calls = leads.map((v) => Math.round(v * 0.72));
  const sprints = calls.map((v) => Math.round(v * 0.62));
  const setups = sprints.map((v) => Math.max(1, Math.round(v * 0.56)));
  const margin = gross.map((v, i) => clamp((net[i] / Math.max(v, 1)) * 100, 70, 98));
  const milestones = nps.map((v, i) => clamp(62 + i * 4 + (v - 70) * 0.32, 60, 96));
  const current = trend[trend.length - 1] ?? base;
  const previous = trend[trend.length - 2] ?? current;
  const mrrCurrent = mrr[mrr.length - 1];
  const mrrPrev = mrr[mrr.length - 2] || mrrCurrent;
  const northStarTarget = convertMoneyValue(100000);
  const northStar = clamp((mrrCurrent / Math.max(northStarTarget, 1)) * 100, 0, 150);
  const weakestChannel = [...channel].sort((a, b) => b.noShowRate - a.noShowRate)[0];
  const strongestChannel = [...channel].sort((a, b) => b.grossRevenue - a.grossRevenue)[0];
  const cashBurn = gross[gross.length - 1] - net[net.length - 1];
  const cashEfficiency = net[net.length - 1] / Math.max(gross[gross.length - 1], 1);
  const setupRate = (setups[setups.length - 1] / Math.max(leads[leads.length - 1], 1)) * 100;
  const topRisk = noShow[noShow.length - 1] > 10
    ? `${copy.legends.noShow} ${copy.statuses.attention.toLowerCase()} em ${fPct(noShow[noShow.length - 1], locale)}`
    : cancel[cancel.length - 1] > 3
      ? `${copy.legends.churn} ${copy.statuses.monitor.toLowerCase()} em ${fPct(cancel[cancel.length - 1], locale)}`
      : language === "EN"
        ? "Operating base without critical rupture in the cycle"
        : language === "ES"
          ? "Base operativa sin ruptura critica en el ciclo"
          : "Base operacional sem ruptura critica no ciclo";
  const topOpportunity = strongestChannel
    ? language === "EN"
      ? `Best monetization channel: ${strongestChannel.name}`
      : language === "ES"
        ? `Canal con mejor monetizacion: ${strongestChannel.name}`
        : `Canal com melhor monetizacao: ${strongestChannel.name}`
    : language === "EN"
      ? "Scale the channel with the most efficient CAC"
      : language === "ES"
        ? "Escalar el canal con CAC mas eficiente"
        : "Escalar canais com CAC mais eficiente";
  const trendPct = (a: number, b: number, suffix = "") => `${a >= b ? "+" : ""}${(((a - b) / Math.max(b, 1)) * 100).toLocaleString(locale, { maximumFractionDigits: 1 })}%${suffix}`;
  return {
    subtitle: `${copy.executiveTitle} · ${l[0]} - ${l[l.length - 1]} · ${copy.generatedAt} ${fmtAt(payload)}`,
    summary: [
      { label: language === "EN" ? "Current MRR" : language === "ES" ? "MRR Actual" : "MRR Atual", value: fMoneyShort(mrrCurrent, currency, locale, language), trend: trendPct(mrrCurrent, mrrPrev, " m/m"), status: copy.statuses.onTrack, color: GREEN },
      { label: "North Star Progress", value: fPct(northStar, locale), trend: `+ ${copy.statuses.growing}`, status: copy.statuses.inProgress, color: GREEN },
      { label: language === "EN" ? "Monthly Churn" : language === "ES" ? "Churn Mensual" : "Churn Mensal", value: fPct(cancel[cancel.length - 1], locale), trend: language === "EN" ? "- Improving" : language === "ES" ? "- Mejora" : "- Melhora", status: cancel[cancel.length - 1] <= 3 ? copy.statuses.healthy : copy.statuses.attention, color: cancel[cancel.length - 1] <= 3 ? GREEN : AMBER },
      { label: "NRR", value: fPct(Math.round(nrr[nrr.length - 1]), locale), trend: language === "EN" ? "+ Expansion" : language === "ES" ? "+ Expansion" : "+ Expansao", status: nrr[nrr.length - 1] >= 110 ? copy.statuses.excellent : copy.statuses.monitor, color: nrr[nrr.length - 1] >= 110 ? GREEN : AMBER },
      { label: language === "EN" ? "Average NPS (C3)" : language === "ES" ? "NPS Medio (C3)" : "NPS Medio (C3)", value: fInt(nps[nps.length - 1], locale), trend: `+ ${Math.max(0, Math.round(nps[nps.length - 1] - nps[nps.length - 2]))} pts`, status: nps[nps.length - 1] >= 80 ? copy.statuses.promoter : copy.statuses.neutral, color: nps[nps.length - 1] >= 80 ? GREEN : AMBER },
      { label: language === "EN" ? "Agenda No-Show" : language === "ES" ? "No-Show Agenda" : "No-Show Agenda", value: fPct(noShow[noShow.length - 1], locale), trend: language === "EN" ? "- Reducing" : language === "ES" ? "- Reduciendo" : "- Reduzindo", status: noShow[noShow.length - 1] <= 10 ? copy.statuses.belowTarget : copy.statuses.attention, color: noShow[noShow.length - 1] <= 10 ? GREEN : AMBER },
      { label: language === "EN" ? "Agenda Occupancy" : language === "ES" ? "Ocupacion Agenda" : "Ocupacao Agenda", value: fPct(occupancy[occupancy.length - 1], locale), trend: `+ ${language === "EN" ? "Increasing" : language === "ES" ? "Aumentando" : "Aumentando"}`, status: occupancy[occupancy.length - 1] >= 85 ? copy.statuses.nearTarget : copy.statuses.evolving, color: occupancy[occupancy.length - 1] >= 85 ? GREEN : AMBER },
      { label: language === "EN" ? "Gross Revenue" : language === "ES" ? "Facturacion Bruta" : "Faturamento Bruto", value: fMoneyShort(gross[gross.length - 1], currency, locale, language), trend: trendPct(gross[gross.length - 1], gross[gross.length - 2] || gross[gross.length - 1], " m/m"), status: copy.statuses.growing, color: GREEN },
    ],
    notes: [
      { title: copy.notes.northStar, body: language === "EN" ? `${fPct(northStar, locale)} progress toward the ${fMoney(northStarTarget, currency, locale)} target with current MRR at ${fMoneyShort(mrrCurrent, currency, locale, language)}.` : language === "ES" ? `${fPct(northStar, locale)} de avance hacia la meta de ${fMoney(northStarTarget, currency, locale)} con MRR actual en ${fMoneyShort(mrrCurrent, currency, locale, language)}.` : `Avanco de ${fPct(northStar, locale)} da meta de ${fMoney(northStarTarget, currency, locale)} com MRR atual em ${fMoneyShort(mrrCurrent, currency, locale, language)}.`, color: BLUE },
      { title: copy.notes.mainRisk, body: topRisk, color: noShow[noShow.length - 1] > 10 || cancel[cancel.length - 1] > 3 ? RED : GREEN },
      { title: copy.notes.opportunity, body: topOpportunity, color: AMBER },
      { title: copy.notes.cashEfficiency, body: language === "EN" ? `${fPct(cashEfficiency * 100, locale)} gross-to-net conversion. Estimated leakage: ${fMoneyShort(cashBurn, currency, locale, language)}.` : language === "ES" ? `${fPct(cashEfficiency * 100, locale)} de conversion de bruto a neto. Fuga estimada: ${fMoneyShort(cashBurn, currency, locale, language)}.` : `${fPct(cashEfficiency * 100, locale)} de conversao de bruto em liquido. Vazamento estimado: ${fMoneyShort(cashBurn, currency, locale, language)}.`, color: BLUE },
    ],
    priorities: [
      language === "EN" ? `Protect recurring expansion: NRR at ${Math.round(nrr[nrr.length - 1])}% and setup rate at ${fPct(setupRate, locale)}.` : language === "ES" ? `Preservar expansion recurrente: NRR en ${Math.round(nrr[nrr.length - 1])}% y setup rate en ${fPct(setupRate, locale)}.` : `Preservar expansao recorrente: NRR em ${Math.round(nrr[nrr.length - 1])}% e setup rate em ${fPct(setupRate, locale)}.`,
      language === "EN" ? `Reduce financial leakage: ${fMoneyShort(cashBurn, currency, locale, language)} between gross and net in the latest cycle.` : language === "ES" ? `Reducir fuga financiera: ${fMoneyShort(cashBurn, currency, locale, language)} entre bruto y neto en el ultimo ciclo.` : `Reduzir vazamento financeiro: ${fMoneyShort(cashBurn, currency, locale, language)} entre bruto e liquido no ultimo ciclo.`,
      language === "EN" ? `Act on agenda to gain occupancy: ${fPct(occupancy[occupancy.length - 1], locale)} with no-show at ${fPct(noShow[noShow.length - 1], locale)}.` : language === "ES" ? `Actuar en agenda para ganar ocupacion: ${fPct(occupancy[occupancy.length - 1], locale)} con no-show en ${fPct(noShow[noShow.length - 1], locale)}.` : `Atuar em agenda para ganhar ocupacao: ${fPct(occupancy[occupancy.length - 1], locale)} com no-show em ${fPct(noShow[noShow.length - 1], locale)}.`,
      language === "EN" ? `Scale the best-performing channel and review the weakest one${weakestChannel ? ` (${weakestChannel.name})` : ""}.` : language === "ES" ? `Escalar el canal de mejor retorno y revisar el mas debil${weakestChannel ? ` (${weakestChannel.name})` : ""}.` : `Escalar canal de melhor retorno e revisar canal mais fraco${weakestChannel ? ` (${weakestChannel.name})` : ""}.`,
    ],
    blocks: [
      { section: copy.sections.revenue, title: `${copy.charts.mrrVsTarget} ${fMoney(northStarTarget, currency, locale)}`, analysis: language === "EN" ? `- MRR moved from ${fMoneyShort(mrr[0], currency, locale, language)} to ${fMoneyShort(mrr[mrr.length - 1], currency, locale, language)}. The latest cycle still points to acceleration, with churn reduction as the key lever.` : language === "ES" ? `- El MRR paso de ${fMoneyShort(mrr[0], currency, locale, language)} a ${fMoneyShort(mrr[mrr.length - 1], currency, locale, language)}. El ultimo ciclo sigue mostrando aceleracion, con reduccion de churn como palanca central.` : `- MRR cresceu de ${fMoneyShort(mrr[0], currency, locale, language)} para ${fMoneyShort(mrr[mrr.length - 1], currency, locale, language)}. O ultimo ciclo mostra aceleracao consistente, com prioridade em reduzir churn para ganhar eficiencia.`, sourceKpis: "MRR, Churn, NRR, CAC, LTV", sourceSystem: language === "EN" ? "Contracts spreadsheet" : language === "ES" ? "Planilla de contratos" : "Planilha de contratos", kind: "barLine", labels: l, a: mrr, b: l.map(() => northStarTarget), target: northStarTarget, labelA: copy.legends.mrr, labelB: "North Star", valueFormat: "money", targetLabel: copy.legends.target },
      { section: copy.sections.revenue, title: copy.charts.churnVsNrr, analysis: language === "EN" ? `- Churn moved from ${fPct(cancel[0], locale)} to ${fPct(cancel[cancel.length - 1], locale)}. NRR ends at ${Math.round(nrr[nrr.length - 1])}%, proving expansion above losses.` : language === "ES" ? `- El churn paso de ${fPct(cancel[0], locale)} a ${fPct(cancel[cancel.length - 1], locale)}. El NRR cierra en ${Math.round(nrr[nrr.length - 1])}%, confirmando expansion por encima de las perdidas.` : `- Churn saiu de ${fPct(cancel[0], locale)} para ${fPct(cancel[cancel.length - 1], locale)}. NRR termina em ${Math.round(nrr[nrr.length - 1])}%, confirmando expansao acima das perdas.`, sourceKpis: "MRR, Churn, NRR, CAC, LTV", sourceSystem: language === "EN" ? "Contracts spreadsheet" : language === "ES" ? "Planilla de contratos" : "Planilha de contratos", kind: "dualAxis", labels: l, a: cancel, b: nrr, target: 100, labelA: copy.legends.churn, labelB: copy.legends.nrr, valueFormat: "percent", targetLabel: copy.legends.target },
      { section: copy.sections.funnel, title: copy.charts.pipeline, analysis: language === "EN" ? `- Call to setup conversion closed at ${fPct((setups[setups.length - 1] / Math.max(calls[calls.length - 1], 1)) * 100, locale)}. The current bottleneck remains qualified lead volume.` : language === "ES" ? `- La conversion Call a Setup cerro en ${fPct((setups[setups.length - 1] / Math.max(calls[calls.length - 1], 1)) * 100, locale)}. El cuello de botella actual sigue siendo el volumen de leads calificados.` : `- Taxa Call->Setup fechou em ${fPct((setups[setups.length - 1] / Math.max(calls[calls.length - 1], 1)) * 100, locale)}. O gargalo continua em volume qualificado de leads.`, sourceKpis: "Leads, Calls, Sprints, Setups", sourceSystem: language === "EN" ? "CRM / funnel sheet" : language === "ES" ? "Planilla embudo / CRM" : "Planilha funil / CRM", kind: "grouped", labels: l, a: leads, b: calls, c: sprints, d: setups, labelA: copy.legends.leads, labelB: copy.legends.calls, labelC: copy.legends.sprints, labelD: copy.legends.setups, valueFormat: "integer" },
      { section: copy.sections.finance, title: copy.charts.grossNetMargin, analysis: language === "EN" ? `- Net revenue closed at ${fMoneyShort(net[net.length - 1], currency, locale, language)} with margin at ${fPct(margin[margin.length - 1], locale)}. The gap between gross and net remains controlled.` : language === "ES" ? `- El ingreso neto cerro en ${fMoneyShort(net[net.length - 1], currency, locale, language)} con margen de ${fPct(margin[margin.length - 1], locale)}. La diferencia entre bruto y neto sigue controlada.` : `- Receita liquida fechou em ${fMoneyShort(net[net.length - 1], currency, locale, language)} com margem de ${fPct(margin[margin.length - 1], locale)}. O spread entre bruto e liquido permanece controlado.`, sourceKpis: language === "EN" ? "Gross Rev., Net Rev., Margin" : language === "ES" ? "Fact. Bruta, Ing. Neto, Margen" : "Fat. Bruto, Rec. Liquida, Margem", sourceSystem: language === "EN" ? "Financial system / ERP" : language === "ES" ? "Sistema financiero / ERP" : "Sistema Financeiro / ERP", kind: "financial", labels: l, a: gross, b: net, c: margin, labelA: copy.legends.gross, labelB: copy.legends.net, labelC: copy.legends.margin, valueFormat: "money" },
      { section: copy.sections.agenda, title: copy.charts.noShowVsOccupancy, analysis: language === "EN" ? `- No-show closed at ${fPct(noShow[noShow.length - 1], locale)} and occupancy at ${fPct(occupancy[occupancy.length - 1], locale)}.${weakestChannel ? ` Most sensitive channel: ${weakestChannel.name}.` : ""}` : language === "ES" ? `- El no-show cerro en ${fPct(noShow[noShow.length - 1], locale)} y la ocupacion en ${fPct(occupancy[occupancy.length - 1], locale)}.${weakestChannel ? ` Canal mas sensible: ${weakestChannel.name}.` : ""}` : `- No-show encerra em ${fPct(noShow[noShow.length - 1], locale)} e ocupacao em ${fPct(occupancy[occupancy.length - 1], locale)}.${weakestChannel ? ` Canal mais sensivel: ${weakestChannel.name}.` : ""}`, sourceKpis: language === "EN" ? "No-Show, Occupancy, Lead Time" : language === "ES" ? "No-Show, Ocupacion, Lead Time" : "No-Show, Ocupacao, Lead Time", sourceSystem: "CRM / Agenda", kind: "barLine", labels: l, a: noShow, b: occupancy, target: 10, labelA: copy.legends.noShow, labelB: copy.legends.occupancy, colorA: noShow.map((v) => v > 16 ? RED : v > 12 ? AMBER : BLUE), valueFormat: "percent", targetLabel: copy.legends.target },
      { section: copy.sections.projects, title: copy.charts.npsVsMilestones, analysis: language === "EN" ? `- NPS moved from ${fInt(nps[0], locale)} to ${fInt(nps[nps.length - 1], locale)}. On-time milestones follow the same curve, reinforcing operational consistency as a key driver.` : language === "ES" ? `- El NPS paso de ${fInt(nps[0], locale)} a ${fInt(nps[nps.length - 1], locale)}. Los hitos en plazo siguen la misma curva, reforzando la consistencia operativa como driver principal.` : `- NPS saiu de ${fInt(nps[0], locale)} para ${fInt(nps[nps.length - 1], locale)}. Marcos no prazo acompanham a curva, reforcando o peso da consistencia operacional.`, sourceKpis: "NPS, Marcos, Quick Wins", sourceSystem: language === "EN" ? "NPS form + project sheet" : language === "ES" ? "Form NPS + planilla proyectos" : "Form NPS + Pl. projetos", kind: "dualAxis", labels: l, a: nps, b: milestones, target: 85, labelA: copy.legends.nps, labelB: copy.legends.milestones, valueFormat: "integer", targetLabel: copy.legends.target },
      { section: copy.sections.cash, title: copy.charts.cashConversion, analysis: language === "EN" ? `- Revenue-to-cash conversion closed at ${fPct(cashEfficiency * 100, locale)}. The CEO goal here is to reduce friction between billing, receiving and protecting margin.` : language === "ES" ? `- La conversion de ingresos a caja util cerro en ${fPct(cashEfficiency * 100, locale)}. El objetivo del CEO aqui es reducir friccion entre facturar, cobrar y proteger margen.` : `- A conversao de receita em caixa util ficou em ${fPct(cashEfficiency * 100, locale)}. O objetivo do CEO aqui e reduzir friccao entre faturar, receber e proteger margem.`, sourceKpis: language === "EN" ? "Gross, Net, Conversion" : language === "ES" ? "Bruto, Neto, Conversion" : "Bruto, Liquido, Conversao", sourceSystem: language === "EN" ? "Finance / Treasury" : language === "ES" ? "Finanzas / Tesoreria" : "Financeiro / Tesouraria", kind: "dualAxis", labels: l, a: gross.map((g, i) => clamp(((g - net[i]) / Math.max(g, 1)) * 100, 0, 40)), b: margin, target: 15, labelA: copy.legends.leakage, labelB: copy.legends.margin, valueFormat: "percent", targetLabel: copy.legends.target },
      { section: copy.sections.channels, title: copy.charts.channelRevenue, analysis: language === "EN" ? `- Channel view shows where growth can scale with less operational friction. Priority: reinforce the best channel and correct the source with the highest no-show.` : language === "ES" ? `- La vista por canal muestra donde el crecimiento puede escalar con menor friccion operativa. Prioridad: reforzar el mejor canal y corregir el origen con mayor no-show.` : `- A leitura por canal mostra onde o crescimento pode ser escalado com menor friccao operacional. Prioridade: reforcar o melhor canal e corrigir origem com maior no-show.`, sourceKpis: language === "EN" ? "Channel revenue, no-show by source" : language === "ES" ? "Ingreso por canal, no-show por origen" : "Receita canal, No-show origem", sourceSystem: language === "EN" ? "CRM / Media / Agenda" : language === "ES" ? "CRM / Medios / Agenda" : "CRM / Midia / Agenda", kind: "grouped", labels: channel.slice(0, 6).map((c) => c.name), a: channel.slice(0, 6).map((c) => Math.round(convertMoneyValue(c.grossRevenue) / 1000)), b: channel.slice(0, 6).map((c) => Math.round(c.noShowRate)), c: channel.slice(0, 6).map((c) => Math.round(c.occupancyRate)), d: channel.slice(0, 6).map((c) => Math.round(convertMoneyValue(c.avgCAC))), labelA: copy.legends.revenueK, labelB: copy.legends.noShow, labelC: copy.legends.occupancy, labelD: copy.legends.cac, valueFormat: "integer" },
    ],
  };
}
function header(page: PDFPage, reportTitle: string, subtitle: string, bold: PDFFont, regular: PDFFont) {
  page.drawRectangle({ x: 0, y: H - 20, width: W, height: 20, color: ORANGE });
  page.drawText(reportTitle, { x: MX, y: 794, font: bold, size: 18, color: DARK });
  page.drawText(subtitle, { x: MX, y: 776, font: regular, size: 10, color: GRAY });
  page.drawLine({ start: { x: MX, y: 766 }, end: { x: W - MX, y: 766 }, thickness: 1, color: GRID });
}
function footer(page: PDFPage, at: string, pageNo: number, total: number, copy: ReportCopy, regular: PDFFont) {
  page.drawLine({ start: { x: MX, y: 48 }, end: { x: W - MX, y: 48 }, thickness: 0.7, color: GRID });
  page.drawText(`${copy.autoGenerated} · ${at} · ${copy.demoData}`, { x: MX, y: 30, font: regular, size: 7.5, color: GRAY });
  page.drawText(`${copy.page} ${pageNo} ${copy.of} ${total}`, { x: W - 95, y: 30, font: regular, size: 7.5, color: GRAY });
}
function summaryPage(page: PDFPage, report: ReportDefinition, copy: ReportCopy, bold: PDFFont, regular: PDFFont) {
  page.drawText(copy.overview, { x: MX, y: 720, font: bold, size: 9, color: ORANGE });
  page.drawText(copy.executiveTitle, { x: MX, y: 700, font: bold, size: 16, color: DARK });
  const widths = [220, 105, 100, 86]; const headers = [copy.kpi, copy.value, copy.trend, copy.status]; let x = MX;
  page.drawRectangle({ x: MX, y: 664, width: CW, height: 22, color: DARK });
  headers.forEach((h, i) => { page.drawText(h, { x: x + 10, y: 671, font: bold, size: 9, color: WHITE }); x += widths[i]; });
  let y = 642;
  report.summary.forEach((row, i) => {
    if (i % 2 === 1) page.drawRectangle({ x: MX, y: y - 6, width: CW, height: 22, color: LIGHT });
    let cx = MX + 10;
    page.drawText(row.label, { x: cx, y, font: regular, size: 9, color: DARK }); cx += widths[0];
    page.drawText(row.value, { x: cx, y, font: bold, size: 9, color: DARK }); cx += widths[1];
    page.drawText(row.trend, { x: cx, y, font: regular, size: 9, color: DARK }); cx += widths[2];
    page.drawRectangle({ x: cx, y: y + 2, width: 7, height: 7, color: row.color });
    page.drawText(row.status, { x: cx + 12, y, font: regular, size: 9, color: DARK });
    y -= 24;
  });

  const noteTop = 458;
  const noteWidth = (CW - 16) / 2;
  report.notes.forEach((note, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = MX + col * (noteWidth + 16);
    const yTop = noteTop - row * 72;
    page.drawRectangle({ x, y: yTop - 52, width: noteWidth, height: 56, color: LIGHT, borderColor: GRID, borderWidth: 1 });
    page.drawRectangle({ x, y: yTop - 52, width: 4, height: 56, color: note.color });
    page.drawText(note.title, { x: x + 10, y: yTop - 14, font: bold, size: 9, color: DARK });
    text(page, note.body, x + 10, yTop - 28, regular, 8.5, GRAY, noteWidth - 16, 10);
  });

  page.drawText(copy.ceoPriorities, { x: MX, y: 302, font: bold, size: 11, color: DARK });
  let py = 282;
  report.priorities.forEach((item) => {
    page.drawCircle({ x: MX + 4, y: py + 4, size: 2.5, color: ORANGE });
    py = text(page, item, MX + 12, py, regular, 8.8, GRAY, CW - 12, 11) - 4;
  });
}
function drawGrid(page: PDFPage, x: number, y: number, w: number, h: number) { for (let i = 1; i <= 4; i += 1) { const gy = y + (h / 5) * i; page.drawLine({ start: { x, y: gy }, end: { x: x + w, y: gy }, thickness: 0.6, color: GRID }); } }
function legend(page: PDFPage, x: number, y: number, color: ReturnType<typeof rgb>, label: string, regular: PDFFont) { page.drawRectangle({ x, y, width: 8, height: 8, color }); page.drawText(label, { x: x + 12, y: y + 1, font: regular, size: 7.5, color: GRAY }); }
function categories(page: PDFPage, labels: string[], x: number, y: number, w: number, regular: PDFFont) { const step = w / labels.length; labels.forEach((l, i) => page.drawText(l, { x: x + step * i + step * 0.18, y, font: regular, size: 7, color: GRAY })); }
function frame(page: PDFPage, title: string, x: number, top: number, w: number, h: number, bold: PDFFont) { page.drawText(title, { x, y: top, font: bold, size: 10.5, color: DARK }); const y = top - 18 - h; page.drawRectangle({ x, y, width: w, height: h, color: WHITE, borderColor: GRID, borderWidth: 1 }); return { x, y, w, h }; }
function chartValueLabel(block: ChartBlock, value: number, currency: string, locale: string, language: "PT" | "EN" | "ES") {
  if (block.valueFormat === "money") return fMoneyShort(value, currency, locale, language);
  if (block.valueFormat === "percent") return fPct(value, locale);
  return fInt(value, locale);
}
function drawChart(page: PDFPage, block: ChartBlock, x: number, top: number, w: number, h: number, regular: PDFFont, bold: PDFFont, language: "PT" | "EN" | "ES", currency: string, locale: string) {
  const f = frame(page, block.title, x, top, w, h, bold); const cx = f.x + 24; const cy = f.y + 26; const cw = f.w - 36; const ch = f.h - 40; drawGrid(page, cx, cy, cw, ch); const step = cw / block.labels.length;
  if (block.kind === "grouped") {
    const max = Math.max(...block.a, ...block.b, ...(block.c || []), ...(block.d || [])) * 1.15; const bw = step * 0.14;
    [block.a, block.b, block.c || [], block.d || []].forEach((series, si) => series.forEach((v, i) => page.drawRectangle({ x: cx + step * i + step * 0.12 + si * (bw + 3), y: cy, width: bw, height: (v / max) * ch, color: [BLUE, ORANGE_SOFT, GREEN, AMBER][si] })));
    legend(page, f.x + 8, f.y + f.h - 12, BLUE, block.labelA || "A", regular); legend(page, f.x + 88, f.y + f.h - 12, ORANGE_SOFT, block.labelB || "B", regular); legend(page, f.x + 168, f.y + f.h - 12, GREEN, block.labelC || "C", regular); legend(page, f.x + 248, f.y + f.h - 12, AMBER, block.labelD || "D", regular);
  } else if (block.kind === "financial") {
    const max = Math.max(...block.a, ...block.b) * 1.12; const maxLine = Math.max(...(block.c || [95]), 95); const bw = step * 0.2; const pts: Array<{ x: number; y: number }> = [];
    block.labels.forEach((_l, i) => { const bx = cx + step * i + step * 0.25; page.drawRectangle({ x: bx, y: cy, width: bw, height: (block.a[i] / max) * ch, color: ORANGE_SOFT }); page.drawRectangle({ x: bx + bw + 4, y: cy, width: bw, height: (block.b[i] / max) * ch, color: ORANGE }); pts.push({ x: bx + bw, y: cy + (((block.c || [])[i] || 0) / maxLine) * ch }); });
    pts.forEach((p, i) => { if (i > 0) page.drawLine({ start: pts[i - 1], end: p, thickness: 1.3, color: GREEN }); page.drawCircle({ x: p.x, y: p.y, size: 2.5, color: GREEN }); });
    legend(page, f.x + 8, f.y + f.h - 12, ORANGE_SOFT, block.labelA || "Bruto", regular); legend(page, f.x + 86, f.y + f.h - 12, ORANGE, block.labelB || "Liquido", regular); legend(page, f.x + 164, f.y + f.h - 12, GREEN, block.labelC || "Margem", regular);
  } else {
    const maxA = Math.max(...block.a) * 1.2; const maxB = Math.max(...block.b, block.target || 0) * 1.1; const bw = step * 0.42; const pts: Array<{ x: number; y: number }> = [];
    if (block.target) { const ty = cy + ((block.target / maxB) * ch); page.drawLine({ start: { x: cx, y: ty }, end: { x: cx + cw, y: ty }, thickness: 1, color: AMBER }); }
    block.a.forEach((v, i) => {
      const bx = cx + step * i + step * 0.28; const colors = Array.isArray(block.colorA) ? block.colorA : []; const barColor = colors[i] || BLUE;
      page.drawRectangle({ x: bx, y: cy, width: bw, height: (v / maxA) * ch, color: barColor });
      page.drawText(chartValueLabel(block, v, currency, locale, language), { x: bx - 2, y: cy + (v / maxA) * ch + 6, font: regular, size: 6.5, color: barColor });
      pts.push({ x: bx + bw / 2, y: cy + ((block.b[i] / maxB) * ch) });
    });
    pts.forEach((p, i) => { if (i > 0) page.drawLine({ start: pts[i - 1], end: p, thickness: 1.3, color: GREEN }); page.drawCircle({ x: p.x, y: p.y, size: 2.5, color: GREEN }); });
    legend(page, f.x + 8, f.y + f.h - 12, BLUE, block.labelA || "Serie A", regular); legend(page, f.x + 94, f.y + f.h - 12, GREEN, block.labelB || "Serie B", regular); if (block.target) legend(page, f.x + 178, f.y + f.h - 12, AMBER, block.targetLabel || "Meta", regular);
  }
  categories(page, block.labels, cx, f.y + 10, cw, regular);
}
function block(page: PDFPage, item: ChartBlock, top: number, regular: PDFFont, bold: PDFFont, language: "PT" | "EN" | "ES", currency: string, locale: string) {
  page.drawText(item.section, { x: MX, y: top, font: bold, size: 12, color: DARK });
  drawChart(page, item, MX, top - 18, CW, 150, regular, bold, language, currency, locale);
  text(page, item.analysis, MX, top - 208, regular, 9, GRAY, CW, 12);
}
function sources(page: PDFPage, items: ChartBlock[], copy: ReportCopy, bold: PDFFont, regular: PDFFont) {
  page.drawText(copy.sourcesTitle, { x: MX, y: 708, font: bold, size: 14, color: DARK });
  const rows = Array.from(new Map(items.map((item) => [item.section, { module: item.section, kpis: item.sourceKpis, source: item.sourceSystem }])).values());
  const widths = [120, 180, 211]; const headers = [copy.sourceHeaders.module, copy.sourceHeaders.kpis, copy.sourceHeaders.system]; let x = MX;
  page.drawRectangle({ x: MX, y: 674, width: CW, height: 22, color: DARK });
  headers.forEach((h, i) => { page.drawText(h, { x: x + 8, y: 681, font: bold, size: 9, color: WHITE }); x += widths[i]; });
  let y = 650;
  rows.forEach((row, i) => {
    if (i % 2 === 1) page.drawRectangle({ x: MX, y: y - 8, width: CW, height: 28, color: LIGHT });
    text(page, row.module, MX + 8, y + 6, regular, 8.5, DARK, widths[0] - 12, 9);
    text(page, row.kpis, MX + widths[0] + 8, y + 6, regular, 8.5, DARK, widths[1] - 12, 9);
    text(page, row.source, MX + widths[0] + widths[1] + 8, y + 6, regular, 8.5, DARK, widths[2] - 12, 9);
    y -= 36;
  });
}
export class PdfAssembler {
  async generate(payload: ExportPayload): Promise<Buffer> {
    const language = normalizeLanguage(payload.language);
    const currency = normalizeCurrency(payload.currency);
    const locale = localeOf(language);
    const rates = await currencyService.getSnapshot(BASE_CURRENCY);
    const pdf = await PDFDocument.create();
    const regular = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const normalizedPayload = { ...payload, language, currency };
    const generatedAt = fmtAt(normalizedPayload);
    const copy = COPY[language];
    const report = buildReport(normalizedPayload, rates);
    const p1 = pdf.addPage([W, H]); header(p1, copy.reportTitle, report.subtitle, bold, regular); summaryPage(p1, report, copy, bold, regular);
    for (let i = 0; i < report.blocks.length; i += 2) {
      const page = pdf.addPage([W, H]);
      header(page, copy.reportTitle, report.subtitle, bold, regular);
      block(page, report.blocks[i], 736, regular, bold, language, currency, locale);
      if (report.blocks[i + 1]) block(page, report.blocks[i + 1], 396, regular, bold, language, currency, locale);
    }
    const pLast = pdf.addPage([W, H]); header(pLast, copy.reportTitle, report.subtitle, bold, regular); sources(pLast, report.blocks, copy, bold, regular);
    const pages = pdf.getPages(); pages.forEach((page, i) => footer(page, generatedAt, i + 1, pages.length, copy, regular));
    return Buffer.from(await pdf.save());
  }
}
export const pdfAssembler = new PdfAssembler();
